# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_auto_20170218_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='article_like',
            field=models.ManyToManyField(blank=True, to='bbs.Article'),
        ),
    ]
