# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0005_auto_20170221_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='click_count',
            field=models.IntegerField(default=0, verbose_name='点击量'),
        ),
        migrations.AddField(
            model_name='article',
            name='disgusting_count',
            field=models.IntegerField(default=0, verbose_name='踩数量'),
        ),
    ]
