# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0006_auto_20170221_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company',
            field=models.CharField(blank=True, default='未填写', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_phone',
            field=models.IntegerField(blank=True, default='未填写', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profession',
            field=models.CharField(blank=True, default='未填写', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signature',
            field=models.CharField(blank=True, default='未填写', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='star',
            field=models.CharField(blank=True, default='未填写', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weibo',
            field=models.CharField(blank=True, default='未填写', max_length=255, null=True),
        ),
    ]
