# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0008_auto_20170221_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_real_name',
            field=models.CharField(blank=True, default='未填写', max_length=255, null=True),
        ),
    ]
