# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0010_auto_20170222_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='experience',
            field=models.IntegerField(default=0, verbose_name='经验值'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_level',
            field=models.CharField(choices=[('bird', '菜鸟'), ('ordinary', '平民'), ('master', '高手'), ('expert', '专家'), ('grandmaster', '大师')], default='菜鸟', max_length=32),
        ),
    ]
