# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0011_auto_20170223_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], default='无', max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_level',
            field=models.CharField(choices=[('香蕉皮', '香蕉皮'), ('小香蕉', '小香蕉'), ('大香蕉', '大香蕉'), ('皮皮香焦', '皮皮香焦'), ('宇宙无敌大香蕉', '宇宙无敌大香蕉')], default='香蕉皮', max_length=32),
        ),
    ]
