# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0012_auto_20170223_1356'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sign_up_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
