# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0013_userprofile_sign_up_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='sex',
            field=models.CharField(choices=[('男', '男'), ('女', '女'), ('未知', '未知')], default='未知', max_length=32),
        ),
    ]
