# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0014_auto_20170225_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='n内容')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('tag', models.CharField(choices=[('笑话', '笑话'), ('荤段子', '荤段子'), ('突发', '突发'), ('时政', '时政'), ('传言', '传言'), ('杂', '杂')], default='杂', max_length=32)),
                ('thumb_count', models.IntegerField(default=0, verbose_name='赞')),
                ('disgusting_count', models.IntegerField(default=0, verbose_name='踩')),
                ('priority', models.IntegerField(default=1000, verbose_name='优先级')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbs.UserProfile')),
            ],
        ),
    ]
