# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0016_shortarticles_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortarticles',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('hidden', '隐藏')], default='published', max_length=32),
        ),
    ]
