# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0017_shortarticles_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortarticles',
            name='title',
            field=models.CharField(max_length=255, verbose_name='标题'),
        ),
    ]
