# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0018_auto_20170305_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortarticles',
            name='content',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='shortarticles',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
