# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0019_auto_20170305_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='short_article_like',
            field=models.ManyToManyField(blank=True, to='bbs.ShortArticles'),
        ),
    ]
