# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clbbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumb_count',
            field=models.IntegerField(default=0, verbose_name='点赞数量'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_thumb_count',
            field=models.IntegerField(default=0, verbose_name='评论点赞数量'),
        ),
        migrations.AlterField(
            model_name='article',
            name='brief',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(upload_to='statics/uploads', verbose_name='文章标题图片'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='head_img',
            field=models.ImageField(blank=True, default='statics/uploads/no-img.jpg', null=True, upload_to='statics/uploads', verbose_name='头像'),
        ),
    ]
